build:
  environment:
    apt_packages:
      - nodejs
      - npm

  nodes:
    static-analysis:
      tests:
        override:
          - command: node -v
          - command: npm -v
          - command: npm config set engine-strict false
          - command: npm ci
          - command: npm run lint || true  # Don't fail the build on lint errors

tools:
  eslint:
    enabled: true
    config:
      use_project_config: true

  javascript_analyzer:
    enabled: true
