version: "3.9"

services:
  mongodb-auth:
    image: mongo:7.0.4
    restart: always
    ports:
      - 27019:27017
    volumes:
      - volume-mongo-auth:/data/db
    networks:
      - network-auth

  auth-server:
    build:
      context: .
    restart: always
    depends_on:
      - mongodb-auth
    environment:
      NODE_ENV: production
      PORT: 3000
      DB_CONNECTION_STRING: mongodb://mongodb-auth:27017/auth
      ACCESS_TOKEN_PRIVATE_KEY_PATH: /private.pem
      ACCESS_TOKEN_LIFE: 2h
      REFRESH_TOKEN_KEY: ${REFRESH_TOKEN_KEY}
      REFRESH_TOKEN_LIFE: 2d
    ports:
      - 5053:3000
    volumes:
      - /home/ubuntu/app/auth-server/private.pem:/private.pem:ro
    networks:
      - network-auth

volumes:
  volume-mongo-auth:

networks:
  network-auth:
